Update

diff --git a/include/data b/include/data
--- a/include/data
+++ b/include/data
@@ -2,7 +2,7 @@
 
 # By Rainman
 # V20222801
-# 0.1.1.2
+# 0.2.0.6
 
 # shellcheck disable=SC2154
 
@@ -57,7 +57,7 @@ grepcidr -f "${LOG_DIR:?}"/node_data/nodes.all "${LOG_DIR:?}"/node_data/nodes.al
 TOTAL_NODES=$(echo "$API_NEW+$ARP_NEW" 2>&1 | bc 2>&1)
 printf '%b' "${LOG_DATE:?} Status() Addnode.Script Total ${G1:?}${TOTAL_NODES:?}${N0:?} Peers!${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
 
-### token price, volume ########################################################
+### coingecko price, volume ####################################################
 
 # make sure curl, html2text and rrdtool exist
 if ! [ -x "$(command -v curl)" ] &>/dev/null; then
@@ -75,38 +75,132 @@ CURRENCY_API="usd"
 
 RANDOM_WAIT=$((((RANDOM % 3) + 1)))
 
-sleep "${RANDOM_WAIT:?}" && torify curl -o "${LOG_DIR:?}"/node_data/stats/ticker.api -X 'GET' 'https://api.coingecko.com/api/v3/coins/'$COIN_API'/market_chart?vs_currency='$CURRENCY_API'&days='$days'' -H 'accept: application/json' &>/dev/null
+sleep "${RANDOM_WAIT:?}" && torify curl -o "${LOG_DIR:?}"/node_data/stats/raw.coingcko -X 'GET' 'https://api.coingecko.com/api/v3/coins/'$COIN_API'/market_chart?vs_currency='$CURRENCY_API'&days='$days'' -H 'accept: application/json' &>/dev/null
 
 # get token price
-grep -o -P '(?<=,).*(?=]],"m)' "${LOG_DIR:?}"/node_data/stats/ticker.api >"${LOG_DIR:?}"/node_data/stats/price 2>&1
+grep -o -P '(?<=,).*(?=]],"m)' "${LOG_DIR:?}"/node_data/stats/raw.coingcko >"${LOG_DIR:?}"/node_data/stats/price.cg 2>&1
 # get token volume
-egrep -o "volumes.*" "${LOG_DIR:?}"/node_data/stats/ticker.api 2>&1 | tr -d '"|:' 2>&1 | awk -F, '{ print $2 }' 2>&1 | awk '{ printf "%.8f\n", $1 }' >"${LOG_DIR:?}"/node_data/stats/volume 2>&1
+egrep -o "volumes.*" "${LOG_DIR:?}"/node_data/stats/raw.coingcko 2>&1 | tr -d '"|:' 2>&1 | awk -F, '{ print $2 }' 2>&1 | awk '{ printf "%.8f\n", $1 }' >"${LOG_DIR:?}"/node_data/stats/volume.cg 2>&1
+
+# api values
+API_PRICE_CG=$(cat "${LOG_DIR:?}"/node_data/stats/price 2>/dev/null | awk '{ printf "%.4f\n", $1 }' 2>&1)
+API_VOLUME_CG=$(cat "${LOG_DIR:?}"/node_data/stats/volume 2>/dev/null | awk '{ printf "%.2f\n", $1 }' 2>&1)
+
+if [[ -z "$API_PRICE_CG" ]] &>/dev/null; then
+  # make sure ticker exist, use rrdtool database, if available
+  rrdtool info /home/"$(whoami)"/stats/value.rrd 2>&1 | grep "last_ds" 2>&1 | awk '{ print $1 }' 2>&1 | awk '{ printf "%.2f\n", $1 }' >"${LOG_DIR:?}"/node_data/stats/price 2>&1
+  # non responsive
+  API_PRICE_CG=$(cat "${LOG_DIR:?}"/node_data/stats/price 2>/dev/null | awk '{ printf "%.2f\n", $1 }' 2>&1)
+fi
+
+if [[ -z "$API_VOLUME_CG" ]] &>/dev/null; then
+  # make sure volume exist, use rrdtool database, if available
+  rrdtool info /home/"$(whoami)"/stats/volume.rrd 2>&1 | grep "last_ds" 2>&1 | awk '{ print $1 }' 2>&1 | awk '{ printf "%.2f\n", $1 }' >"${LOG_DIR:?}"/node_data/stats/volume 2>&1
+  # non responsive
+  API_VOLUME_CG=$(cat "${LOG_DIR:?}"/node_data/stats/volume 2>/dev/null | awk '{ printf "%.2f\n", $1 }' 2>&1)
+fi
+
+printf '%b' "${LOG_DATE:?} Status() Coingcko.Api() Found ${G1:?}${API_PRICE_CG:?}${N0:?} price!${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+printf '%b' "${LOG_DATE:?} Status() Coingcko.Api() Found ${G1:?}${API_VOLUME_CG:?}${N0:?} volume!${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+
+### coinmarketcap price, volume ################################################
+
+cat >/tmp/add_cmc <<'EOF'
+#!/bin/bash
+
+# By Rainman
+# V20222801
+# 0.0.3.1
+
+source /usr/local/bin/include/pitrump.conf
+source /usr/local/bin/include/color
+
+# date for logs
+LOG_DATE=$(cat "${LOG_DIR:?}"/node_data/stats/date 2>/dev/null)
+
+printf '%b' "${LOG_DATE:?} Status() CoinMCap.Api() Fetching CoinMarketCap data!${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+
+# remove requests
+truncate -s 0 "${LOG_DIR:?}"/node_data/requests
+
+for (( ; ; )); do # loop until success
+  clear
+  URL="https://coinmarketcap.com/currencies/trumpcoin/"
+  curl -s -L "$URL" 2>&1 | html2text >"${LOG_DIR:?}"/node_data/stats/raw.coinmcap 2>&1
+  sleep 1
+  echo "fail" >>"${LOG_DIR:?}"/node_data/requests 2>&1
+
+  if grep "trump" "${LOG_DIR:?}"/node_data/stats/raw.coinmcap &>/dev/null; then
+    echo "success" >>"${LOG_DIR:?}"/node_data/requests 2>&1
+    printf '%b' "${LOG_DATE:?} Status() CoinMCap.Api() ${G1:?}Success!${N0:?} Found API Data! After ${CY:?}$(wc -l "${LOG_DIR:?}"/node_data/requests 2>&1 | awk '{ print $1 }' 2>&1)${N0:?} request(s)\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    exit
+  fi
+
+done
+EOF
+
+# reset requests file
+if grep "success" "${LOG_DIR:?}"/node_data/requests &>/dev/null; then
+
+  # get token price
+  grep "Trumpcoin Price" "${LOG_DIR:?}"/node_data/stats/raw.coinmcap 2>&1 | tr -d '$|,' 2>&1 | xargs 2>&1 | egrep -o "Price [0-9]+.[0-9]+" 2>&1 | awk '{ print $2 }' 2>&1 | tail -1 >"${LOG_DIR:?}"/node_data/stats/price.cmc 2>&1
+  # get token volume
+  grep "Trading Volume24h" "${LOG_DIR:?}"/node_data/stats/raw.coinmcap 2>&1 | tail -1 2>&1 | awk '{ print $3 }' 2>&1 | tr -d '$|,' >"${LOG_DIR:?}"/node_data/stats/volume.cmc 2>&1
+  # get token rank
+  grep "Market Rank" "${LOG_DIR:?}"/node_data/stats/raw.coinmcap 2>&1 | tail -1 2>&1 | tr -d '#' 2>&1 | awk '{ print $3 }' >"${LOG_DIR:?}"/node_data/stats/rank.cmc 2>&1
+  # get token watchlist
+  grep "watchlists" "${LOG_DIR:?}"/node_data/stats/raw.coinmcap 2>&1 | tr -d ',' 2>&1 | awk '{ print $2 }' >"${LOG_DIR:?}"/node_data/stats/watchers.cmc 2>&1
+
+  rm "${LOG_DIR:?}"/node_data/requests &>/dev/null
+fi
+
+# look for screen session, if not found, run this block
+if ! screen -list 2>&1 | grep -q "add_cmc" &>/dev/null; then
+
+  # create screen session
+  screen -dmS add_cmc 2>&1
+
+  screen -S add_cmc -X -p 0 stuff $'torify bash /tmp/add_cmc\n'
+else
+  killall screen &>/dev/null
+fi
+
+# if success, continue
+if grep "success" "${LOG_DIR:?}"/node_data/requests &>/dev/null; then
+
+  if [[ -z "$API_PRICE_CMC" ]] &>/dev/null; then
+    # make sure ticker exist, use rrdtool database, if available
+    rrdtool info /home/"$(whoami)"/stats/value.rrd 2>&1 | grep "last_ds" 2>&1 | awk '{ print $1 }' 2>&1 | awk '{ printf "%.2f\n", $1 }' >"${LOG_DIR:?}"/node_data/stats/price 2>&1
+    # non responsive
+    API_PRICE_CMC=$(cat "${LOG_DIR:?}"/node_data/stats/price.cmc 2>/dev/null | awk '{ printf "%.2f\n", $1 }' 2>&1)
+  fi
+
+  if [[ -z "$API_VOLUME_CMC" ]] &>/dev/null; then
+    # make sure volume exist, use rrdtool database, if available
+    rrdtool info /home/"$(whoami)"/stats/volume.rrd 2>&1 | grep "last_ds" 2>&1 | awk '{ print $1 }' 2>&1 | awk '{ printf "%.2f\n", $1 }' >"${LOG_DIR:?}"/node_data/stats/volume 2>&1
+    # non responsive
+    API_VOLUME_CMC=$(cat "${LOG_DIR:?}"/node_data/stats/volume.cmc 2>/dev/null | awk '{ printf "%.2f\n", $1 }' 2>&1)
+  fi
+fi
+
+if [[ -f "${LOG_DIR:?}"/node_data/stats/price.cmc ]] &>/dev/null; then
+  # api values
+  API_PRICE_CMC=$(cat "${LOG_DIR:?}"/node_data/stats/price.cmc 2>/dev/null | awk '{ printf "%.4f\n", $1 }' 2>&1)
+  API_VOLUME_CMC=$(cat "${LOG_DIR:?}"/node_data/stats/volume.cmc 2>/dev/null | awk '{ printf "%.2f\n", $1 }' 2>&1)
+  API_RANK_CMC=$(cat "${LOG_DIR:?}"/node_data/stats/rank.cmc 2>/dev/null | awk '{ printf "%.4f\n", $1 }' 2>&1)
+  API_WATCH_CMC=$(cat "${LOG_DIR:?}"/node_data/stats/watchers.cmc 2>/dev/null | awk '{ printf "%.2f\n", $1 }' 2>&1)
+  printf '%b' "${LOG_DATE:?} Status() CoinMCap.Api() Found ${G1:?}${API_PRICE_CMC:?}${N0:?} price!${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+  printf '%b' "${LOG_DATE:?} Status() CoinMCap.Api() Found ${G1:?}${API_VOLUME_CMC:?}${N0:?} volume!${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+  printf '%b' "${LOG_DATE:?} Status() CoinMCap.Api() Found ${G1:?}${API_RANK_CMC:?}${N0:?} rank!${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+  printf '%b' "${LOG_DATE:?} Status() CoinMCap.Api() Found ${G1:?}${API_WATCH_CMC:?}${N0:?} watchlist!${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+fi
+
+### price, volume average ######################################################
 
 # keep last n of ticker price and volume
 echo "$(tail -14 "${LOG_DIR:?}"/node_data/stats/price.avg 2>&1)" 2>&1 | awk '{ printf "%.8f\n", $1 }' >"${LOG_DIR:?}"/node_data/stats/price.avg.tmp 2>&1
 mv "${LOG_DIR:?}"/node_data/stats/price.avg.tmp "${LOG_DIR:?}"/node_data/stats/price.avg 2>&1
 echo "$(tail -14 "${LOG_DIR:?}"/node_data/stats/volume.avg 2>&1)" 2>&1 | awk '{ printf "%.8f\n", $1 }' >"${LOG_DIR:?}"/node_data/stats/volume.avg.tmp 2>&1
 mv "${LOG_DIR:?}"/node_data/stats/volume.avg.tmp "${LOG_DIR:?}"/node_data/stats/volume.avg 2>&1
-
-# api values
-API_PRICE=$(cat "${LOG_DIR:?}"/node_data/stats/price 2>/dev/null | awk '{ printf "%.4f\n", $1 }' 2>&1)
-API_VOLUME=$(cat "${LOG_DIR:?}"/node_data/stats/volume 2>/dev/null | awk '{ printf "%.2f\n", $1 }' 2>&1)
-
-if [[ -z "$API_PRICE" ]] &>/dev/null; then
-  # make sure ticker exist, use rrdtool database, if available
-  rrdtool info /home/"$(whoami)"/stats/value.rrd 2>&1 | grep "last_ds" 2>&1 | awk '{ print $1 }' 2>&1 | awk '{ printf "%.2f\n", $1 }' >"${LOG_DIR:?}"/node_data/stats/price 2>&1
-  # non responsive
-  API_PRICE=$(cat "${LOG_DIR:?}"/node_data/stats/price 2>/dev/null | awk '{ printf "%.2f\n", $1 }' 2>&1)
-fi
-
-if [[ -z "$API_VOLUME" ]] &>/dev/null; then
-  # make sure volume exist, use rrdtool database, if available
-  rrdtool info /home/"$(whoami)"/stats/volume.rrd 2>&1 | grep "last_ds" 2>&1 | awk '{ print $1 }' 2>&1 | awk '{ printf "%.2f\n", $1 }' >"${LOG_DIR:?}"/node_data/stats/volume 2>&1
-  # non responsive
-  API_VOLUME=$(cat "${LOG_DIR:?}"/node_data/stats/volume 2>/dev/null | awk '{ printf "%.2f\n", $1 }' 2>&1)
-fi
-
-printf '%b' "${LOG_DATE:?} Status() Coingcko.Api() Found ${G1:?}${API_PRICE:?}${N0:?} price!${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-printf '%b' "${LOG_DATE:?} Status() Coingcko.Api() Found ${G1:?}${API_VOLUME:?}${N0:?} volume!${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
 
 # END
