Update

diff --git a/include/download b/include/download
--- a/include/download
+++ b/include/download
@@ -17,24 +17,23 @@ if [[ ! -f /usr/local/bin/freedomcoind && ! -f /usr/local/bin/freedomcoin-cli ]]
   # machine
   UNAME_M="$(uname -m)"
 
-  if [[ "$(echo "$UNAME_M" | grep -c "x86_64")" == "1" ]] &>/dev/null; then
-    # x86_64
+  if [[ "$(echo "$UNAME_M" | grep -c "x86_64")" == "1" ]]; then
     WALLET_DOWNLOAD="FreedomCoin-Core-Linux"
-  fi
-  if [[ "$(echo "$UNAME_M" | grep -c "aarch64")" == "1" ]] &>/dev/null; then
-    # aarch64
+  elif [[ "$(echo "$UNAME_M" | grep -c "aarch64")" == "1" ]]; then
     WALLET_DOWNLOAD="FreedomCoin-aarch64"
-  fi
-  if [[ "$(echo "$UNAME_M" | grep -c "arm")" == "1" ]] &>/dev/null; then
-    # arm
+  elif [[ "$(echo "$UNAME_M" | grep -c "arm")" == "1" ]]; then
     WALLET_DOWNLOAD="FreedomCoin_arm"
   fi
 
   # if missing
-  if [[ ! -f "$HOME"/"$WALLET_DOWNLOAD".zip ]] &>/dev/null; then
-    # change directory, download WALLET_DOWNLOAD.zip
-    cd || exit && wget -c https://github.com/FreedomCoin-Project/FreedomCoin-Core/releases/download/"$LATEST_RELEASE"/"$WALLET_DOWNLOAD".zip
-    printf '%b' "[${G1}OK${N0}] wget    : Download complete!\n"
+  if [[ ! -f "$HOME"/"$WALLET_DOWNLOAD".zip ]]; then
+    cd || exit
+    if wget -c "https://github.com/FreedomCoin-Project/FreedomCoin-Core/releases/download/$LATEST_RELEASE/$WALLET_DOWNLOAD.zip"; then
+      printf '%b' "[${G1}OK${N0}] wget    : Download complete!\n"
+    else
+      printf '%b' "[${R1}!!${N0}] wget    : Download failed, running build script...\n"
+      bash /etc/pi-node/include/build
+    fi
   fi
 
   # if missing
