Update

diff --git a/include/functions b/include/functions
--- a/include/functions
+++ b/include/functions
@@ -2,7 +2,7 @@
 
 # By Rainman
 # V20210812
-# 0.1.1.3
+# 0.1.1.6
 
 # shellcheck disable=SC2034  # Unused variables left for readability
 
@@ -87,7 +87,7 @@ else
   # testnet
   WALLET_CHAIN="testnet"
 fi
-if [ -f "$LOG_DIR"/getblockchaininfo ]; then
+if ! cat "$LOG_DIR"/getblockchaininfo 2>&1 | grep "error" &>/dev/null; then
   # headers, blocks, sync
   HEADS=$(cat "$LOG_DIR"/getblockchaininfo 2>&1 | grep "blocks" 2>&1 | grep -Eo "[0-9]+" 2>&1)
   BLOCK=$(cat "$LOG_DIR"/getblockchaininfo 2>&1 | grep "headers" 2>&1 | grep -Eo "[0-9]+" 2>&1)
