Update

diff --git a/include/functions b/include/functions
--- a/include/functions
+++ b/include/functions
@@ -2,12 +2,12 @@
 
 # By Rainman
 # V20211712
-# 0.6.3.9
+# 0.6.4.9
 
 # shellcheck disable=SC2034  # Unused variables left for readability
 
 # script version for dashbord
-VERSION="v0.6.3.9"
+VERSION="v0.6.4.9"
 
 # auto update of repository
 UPDATE_REPO="0"
@@ -276,18 +276,28 @@ if [[ "$TRIES_COUNT" -lt "$(debug_tries 2>&1)" ]]; then
   debug_tries >"${LOG_DIR:?}"/node_data/tries 2>&1
 fi
 
-### addnodes screen script #####################################################
+# clean up personal addnodes
+cat /home/"$(whoami)"/addnodes 2>&1 |
+  grep -v -f "$LOG_DIR"/node_data/peers/failed >/tmp/addnodes.tmp 2>&1
+mv /tmp/addnodes.tmp /home/"$(whoami)"/addnodes 2>&1
+# clean up script addnodes
+cat "$LOG_DIR"/node_data/addnodes 2>&1 |
+  grep -v -f "$LOG_DIR"/node_data/nodes >/tmp/addnodes.tmp 2>&1
+mv /tmp/addnodes.tmp "$LOG_DIR"/node_data/addnodes 2>&1
+cat /home/"$(whoami)"/addnodes 2>&1 |
 
-# greater than n seconds
-if [[ "$(uptime_daemon)" -gt "369" ]]; then
-  # look for screen session, if not found, start one
-  if ! screen -list 2>&1 |
-    grep -q "addnodes" 2>&1; then
-    # create screen session
-    screen -dmS addnodes 2>&1
+  ### addnodes screen script #####################################################
 
-    # connect nodes found with addnodes list above, (using tmp directory)
-    cat >"${LOG_DIR:?}"/add_peers <<'EOF'
+  # greater than n seconds
+  if [[ "$(uptime_daemon)" -gt "369" ]]; then
+    # look for screen session, if not found, start one
+    if ! screen -list 2>&1 |
+      grep -q "addnodes" 2>&1; then
+      # create screen session
+      screen -dmS addnodes 2>&1
+
+      # connect nodes found with addnodes list above, (using tmp directory)
+      cat >"${LOG_DIR:?}"/add_peers <<'EOF'
 #!/bin/bash
 
 # By Rainman
@@ -321,11 +331,11 @@ killall screen
 screen -wipe
 exit
 EOF
-    # 60s 90s 120s 240s 300s 600s, 900s = 15 minutes
-    # start adding nodes, inside screen session (timeout n seconds)
-    timeout 900 screen -S addnodes -X -p 0 stuff $'bash /tmp/add_peers\n'
+      # 60s 90s 120s 240s 300s 600s, 900s = 15 minutes
+      # start adding nodes, inside screen session (timeout n seconds)
+      timeout 900 screen -S addnodes -X -p 0 stuff $'bash /tmp/add_peers\n'
+    fi
   fi
-fi
 
 ### wallet information #########################################################
 
