Update

diff --git a/include/functions b/include/functions
--- a/include/functions
+++ b/include/functions
@@ -2,12 +2,12 @@
 
 # By Rainman
 # V20220501
-# 1.0.1.4
+# 1.0.1.0
 
 # shellcheck disable=SC2034  # Unused variables left for readability
 
 # script version for dashbord
-VERSION="v1.0.1.4"
+VERSION="v1.0.1.0"
 
 source /home/pi/pitrump.conf
 source /usr/local/bin/include/color
@@ -676,7 +676,7 @@ if ! screen -list 2>&1 | grep -q "add_peers" &>/dev/null; then
     egrep -o "addr: [0-9]+.[0-9]+.[0-9]+.[0-9]+" "${LOG_DIR:?}"/node_data/client/getpeerinfo 2>&1 | awk '{ print $2 }' 2>&1 | awk '!a[$0]++' 2>&1 | sort -n >"${LOG_DIR:?}"/node_data/peers/success 2>&1
   fi
 
-  ### add_peers screen script ####################################################
+  ### add_peers screen script ##################################################
 
   # greater than n seconds, continue
   if [[ "$(cat "${LOG_DIR:?}"/node_data/uptime 2>/dev/null)" -gt "300" ]] &>/dev/null; then
@@ -688,7 +688,7 @@ if ! screen -list 2>&1 | grep -q "add_peers" &>/dev/null; then
 
     cat "${LOG_DIR:?}"/node_data/peers.tmp 2>/dev/null | awk '!a[$0]++' 2>&1 | sort -n >"${LOG_DIR:?}"/node_data/add_peers 2>&1
 
-    ### random address ###########################################################
+    ### random address #########################################################
 
     # generate random ip address (ipv4)
     RIP_IPV4=$(printf "%d.%d.%d.%d\n" "$((RANDOM % 256))" "$((RANDOM % 256))" "$((RANDOM % 256))" "$((RANDOM % 256))" 2>&1)
@@ -698,7 +698,7 @@ if ! screen -list 2>&1 | grep -q "add_peers" &>/dev/null; then
     echo "$RIP_IPV6" >>"${LOG_DIR:?}"/node_data/add_peers 2>&1
     echo "$RIP_IPV4" 2>&1 | grep -vwE "(${IP_ADDRESS_N:?}|127.0.0.1|192.168.1.1|192.168.0.1|192.168.1.10.1|192.168.2.1|192.168.1.254|192.168.0.30|192.168.0.50|10.0.0.2|10.1.1.1|10.0.1.1|10.0.0.1|10.0.0.138|10.10.1.1)" >>"${LOG_DIR:?}"/node_data/add_peers 2>&1
 
-    ### remove failed, connected peers and invalid pattern address ###############
+    ### remove failed, connected peers and invalid pattern address #############
 
     # disregard already connected peers (success list)
     grep -vf "${LOG_DIR:?}"/node_data/peers/success "${LOG_DIR:?}"/node_data/add_peers 2>&1 | sort -n >"${LOG_DIR:?}"/node_data/add_peers.tmp 2>&1
@@ -722,23 +722,19 @@ if ! screen -list 2>&1 | grep -q "add_peers" &>/dev/null; then
       killall screen &>/dev/null
       printf '%b' "${LOG_DATE:?} Status() Addnode.Script screen dead ??? it's dead now.${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
     fi
-  fi
 
-  # look for screen session, if not found, start one
-  if ! screen -list 2>&1 | grep -q "add_peers" &>/dev/null; then
-    # create screen session
-    screen -dmS add_peers 2>&1
+    # look for screen session, if not found, start one
+    if ! screen -list 2>&1 | grep -q "add_peers" &>/dev/null; then
+      # create screen session
+      screen -dmS add_peers 2>&1
 
-    # create temp and backup list for connection check
-    cp "${LOG_DIR:?}"/node_data/add_peers "${LOG_DIR:?}"/node_data/add_peers.check 2>&1
+      # create temp and backup list for connection check
+      cp "${LOG_DIR:?}"/node_data/add_peers "${LOG_DIR:?}"/node_data/add_peers.check 2>&1
 
-    if [ ! -s "${LOG_DIR:?}"/node_data/stats/connections ] &>/dev/null; then
-      # make sure connections exist
-      echo "1" >"${LOG_DIR:?}"/node_data/stats/connections 2>&1
-    fi
-
-    # greater than n seconds, continue
-    if [[ "$(cat "${LOG_DIR:?}"/node_data/uptime 2>/dev/null)" -gt "300" ]] &>/dev/null; then
+      if [ ! -s "${LOG_DIR:?}"/node_data/stats/connections ] &>/dev/null; then
+        # make sure connections exist
+        echo "1" >"${LOG_DIR:?}"/node_data/stats/connections 2>&1
+      fi
 
       # make sure add_peers exist
       if [[ ! -f "${LOG_DIR:?}"/add_peers ]] &>/dev/null; then
