Update

diff --git a/include/functions b/include/functions
--- a/include/functions
+++ b/include/functions
@@ -2,12 +2,12 @@
 
 # By Rainman
 # V20212312
-# 0.9.4.6
+# 0.9.4.9
 
 # shellcheck disable=SC2034  # Unused variables left for readability
 
 # script version for dashbord
-VERSION="v0.9.4.6"
+VERSION="v0.9.4.9"
 
 source /home/pi/pitrump.conf
 source /usr/local/bin/include/color
@@ -238,110 +238,113 @@ if [[ "$(date '+%T' 2>&1 | egrep "[0-9]+:30:[0-9]+|[0-9]+:00:[0-9]+" 2>&1)" ]] &
   printf '%b' "${LOG_DATE:?} Status() Update.Nodes() Cleaning personal addnodes! Removed ${GR:?}${PERSONAL_ADDNODES_DIFF:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
 fi
 
-# greater than n seconds
-if [[ "$(uptime_daemon)" -gt "600" ]] &>/dev/null; then
+# get node list, ticker (api, arp)
+if [ ! -f "${LOG_DIR:?}"/node_data/nodes ] &>/dev/null; then
+  # greater than n seconds
+  if [[ "$(uptime_daemon)" -gt "600" ]] &>/dev/null; then
 
-  # curl, arp data source
-  source /usr/local/bin/include/data
+    # curl, arp data source
+    source /usr/local/bin/include/data
 
-  # make sure script addnodes list, avgconfirmation exist
-  touch "${LOG_DIR:?}"/node_data/addnodes.script &>/dev/null
+    # make sure script addnodes list, avgconfirmation exist
+    touch "${LOG_DIR:?}"/node_data/addnodes.script &>/dev/null
 
-  # count failed connections, feed output to debug.log
-  FAIL_COUNT=$(wc -l "${LOG_DIR:?}"/node_data/peers/failed 2>&1 | awk '{ print $1 }' 2>&1)
-  ADDNODE_SI=$(wc -l "${LOG_DIR:?}"/node_data/addnodes.script 2>&1 | awk '{ print $1 }' 2>&1)
-  ADDNODE_NOD=$(wc -l "${LOG_DIR:?}"/node_data/nodes 2>&1 | awk '{ print $1 }' 2>&1)
-  ADDNODE_PSI=$(wc -l "${LOG_DIR:?}"/node_data/addnodes.personal 2>&1 | awk '{ print $1 }' 2>&1)
+    # count failed connections, feed output to debug.log
+    FAIL_COUNT=$(wc -l "${LOG_DIR:?}"/node_data/peers/failed 2>&1 | awk '{ print $1 }' 2>&1)
+    ADDNODE_SI=$(wc -l "${LOG_DIR:?}"/node_data/addnodes.script 2>&1 | awk '{ print $1 }' 2>&1)
+    ADDNODE_NOD=$(wc -l "${LOG_DIR:?}"/node_data/nodes 2>&1 | awk '{ print $1 }' 2>&1)
+    ADDNODE_PSI=$(wc -l "${LOG_DIR:?}"/node_data/addnodes.personal 2>&1 | awk '{ print $1 }' 2>&1)
 
-  # note: heavy reading, with time
-  if [[ "$(date '+%T' 2>&1 | egrep "[0-9]+:[0-9]+5:[0-9]+|[0-9]+:[0-9]+0:[0-9]+" 2>&1)" ]] &>/dev/null; then
-    grep -c "New outbound peer" "${WALLET_LOG_DIR:?}"/debug.log >"${LOG_DIR:?}"/node_data/success.value 2>&1
-    SUCCESS_CO=$(cat "${LOG_DIR:?}"/node_data/success.value 2>/dev/null)
-  elif [[ -z "$SUCCESS_CO" ]] &>/dev/null; then
+    # note: heavy reading, with time
+    if [[ "$(date '+%T' 2>&1 | egrep "[0-9]+:[0-9]+5:[0-9]+|[0-9]+:[0-9]+0:[0-9]+" 2>&1)" ]] &>/dev/null; then
+      grep -c "New outbound peer" "${WALLET_LOG_DIR:?}"/debug.log >"${LOG_DIR:?}"/node_data/success.value 2>&1
+      SUCCESS_CO=$(cat "${LOG_DIR:?}"/node_data/success.value 2>/dev/null)
+    elif [[ -z "$SUCCESS_CO" ]] &>/dev/null; then
+      # non responsive
+      SUCCESS_CO="0"
+    else
+      SUCCESS_CO=$(cat "${LOG_DIR:?}"/node_data/success.value 2>/dev/null)
+    fi
+
+    SUCCESS_RA=$(echo "100/$(echo "$FAIL_COUNT+$SUCCESS_CO" 2>&1 |
+      bc -l 2>&1)*$SUCCESS_CO" 2>&1 | bc -l 2>&1 | awk '{ printf "%.2f\n", $1 }' 2>&1)
+
+    # syntax fix
+    SUCCESS_RA_SX=$(echo "$SUCCESS_RA" 2>&1 | awk -F. '{ print $1 }' 2>&1)
     # non responsive
-    SUCCESS_CO="0"
+    if [[ -z "$SUCCESS_RA_SX" ]] &>/dev/null; then
+      SUCCESS_RA_SX="0"
+    fi
+
+    # success rate with color
+    if [[ "$SUCCESS_RA_SX" -ge "0" ]] &>/dev/null; then
+      SRAC="${GR:?}${SUCCESS_RA:?}%"
+    fi
+    if [[ "$SUCCESS_RA_SX" -ge "10" ]] &>/dev/null; then
+      SRAC="${Y0:?}${SUCCESS_RA:?}%"
+    fi
+    if [[ "$SUCCESS_RA_SX" -ge "25" ]] &>/dev/null; then
+      SRAC="${Y1:?}${SUCCESS_RA:?}%"
+    fi
+    if [[ "$SUCCESS_RA_SX" -ge "50" ]] &>/dev/null; then
+      SRAC="${G0:?}${SUCCESS_RA:?}%"
+    fi
+    if [[ "$SUCCESS_RA_SX" -ge "75" ]] &>/dev/null; then
+      SRAC="${G1:?}${SUCCESS_RA:?}%"
+    fi
+
+    ONION_R=$(cat "${LOG_DIR:?}"/node_data/onion 2>/dev/null)
+    WANIP_R=$(grep "address" "${LOG_DIR:?}"/node_data/getwan 2>&1 |
+      egrep -o "[0-9]+.[0-9]+.[0-9]+.[0-9]+" 2>&1)
+
+    if [[ -z "$ONION_R" ]] &>/dev/null; then
+      # non responsive
+      ONION_R="none"
+    fi
+    if [[ -z "$WANIP_R" ]] &>/dev/null; then
+      # non responsive
+      WANIP_R="none"
+    fi
+
+    # repository head, date and time
+    LATEST_HEAD=$(cd /home/"$(whoami)"/trump-node || exit && git rev-parse --short HEAD 2>&1 |
+      grep -Eo '[a0-z9]{7}' 2>&1 | head -1 2>&1)
+    LATEST_DATE=$(cd /home/"$(whoami)"/trump-node || exit && git log -1 --format="%at" |
+      xargs -I{} date -d @{} '+%Y/%m/%d')
+    LATEST_TIME=$(cd /home/"$(whoami)"/trump-node || exit && git log -1 --format="%at" |
+      xargs -I{} date -d @{} '+%H:%M:%S')
+
+    # average confirmations (average staking/reward time)
+    UNSPENT_COUNT=$(grep "confirmations" "${LOG_DIR:?}"/node_data/listunspent 2>&1 | wc -l 2>&1)
+    UNSPENT_TOTAL=$(grep "confirmations" "${LOG_DIR:?}"/node_data/listunspent 2>&1 |
+      awk '{ print $2 }' 2>&1 | awk '{ SUM += $1} END { print SUM }' 2>&1)
+    # average calculated
+    UNSPENT_AVG=$(echo "$UNSPENT_TOTAL/$UNSPENT_COUNT" 2>&1 | bc 2>&1)
+    # calculate seconds
+    UNSPENT_SEC=$(echo "$UNSPENT_AVG*60" 2>&1 |
+      bc -l 2>&1 | awk -F. '{ print $1 }' 2>&1)
+    # calculate seconds into age
+    UNSPENT_AGE=$(printf '%dh:%dm' $(("$UNSPENT_SEC/3600")) $(("$UNSPENT_SEC%3600/60")))
+    # save the value
+    echo "${UNSPENT_AGE:?}" >"${LOG_DIR:?}"/node_data/avgconfirmation.value
+    UNSPENT_AGE_D=$(echo "$(echo "$UNSPENT_AGE" 2>&1 |
+      egrep -o "[0-9]+h" 2>&1 | tr -d 'h' 2>&1)/24" 2>&1 | bc 2>&1)
+
+    printf '%b' "${GR:?} - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    printf '%b' "${GR:?}${LOG_DATE:?} Status() SystemTorNet()${N0:?} Onion ${ONION_R:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    printf '%b' "${GR:?}${LOG_DATE:?} Status() SystemInternet${N0:?} WanIP ${WANIP_R:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    printf '%b' "${GR:?}${LOG_DATE:?} Status() SystemIntranet${N0:?} Local ${IP_ADDRESS_N:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    printf '%b' "${GR:?}${LOG_DATE:?} Status() Script.version${N0:?} Repository [${G1:?}${LATEST_HEAD:?}${N0:?}] ${LATEST_DATE:?} ${LATEST_TIME:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    printf '%b' "${GR:?}${LOG_DATE:?} Status() System.Monitor${N0:?} Load ${LOAD:?} - temp ${CPU_CTEMP:?}°C ${CPU_FTEMP:?}°F ${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    printf '%b' "${GR:?}${LOG_DATE:?} Status() System.Monitor${N0:?} Free Mem ${FREE_MEM:?}/${TOTAL_MEM:?} - HDDuse ${USED_HDD:?} (${USED_HDD_P:?})${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    printf '%b' "${GR:?}${LOG_DATE:?} Status() Fail/success()${N0:?} Fail ${R1:?}${FAIL_COUNT:?}${N0:?} Success ${G1:?}$SUCCESS_CO${N0:?} Success Rate ${SRAC:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    printf '%b' "${GR:?}${LOG_DATE:?} Status() Addnode.Size()${N0:?} Add New Peers ${CY:?}${ADDNODE_SI:?}${N0:?} Addnode Peers ${C1:?}$ADDNODE_PSI${N0:?} Curl/Arp Nodes ${G1:?}$ADDNODE_NOD${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    printf '%b' "${GR:?}${LOG_DATE:?} Status() Peers.Status()${N0:?} Total ${WALLET_PEERS_TOTAL:?} Latest ${WALLET_PEERS_LATEST:?} Older ${WALLET_PEERS_OTHER:?} - ${G1:?}⇩${N0:?} $DOWNLOAD ${R1:?}⇧${N0:?} $UPLOAD${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    printf '%b' "${GR:?}${LOG_DATE:?} Status() Proof.Of.Work:${N0:?} PoS ${WALLET_STAKES:?} AVG Time (${UNSPENT_AGE_D:?}d) ${GR:?}${UNSPENT_AGE:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    printf '%b' "${GR:?} - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
   else
-    SUCCESS_CO=$(cat "${LOG_DIR:?}"/node_data/success.value 2>/dev/null)
+    printf '%b' "${LOG_DATE:?} Status() System.Monitor Loading wallet${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
   fi
-
-  SUCCESS_RA=$(echo "100/$(echo "$FAIL_COUNT+$SUCCESS_CO" 2>&1 |
-    bc -l 2>&1)*$SUCCESS_CO" 2>&1 | bc -l 2>&1 | awk '{ printf "%.2f\n", $1 }' 2>&1)
-
-  # syntax fix
-  SUCCESS_RA_SX=$(echo "$SUCCESS_RA" 2>&1 | awk -F. '{ print $1 }' 2>&1)
-  # non responsive
-  if [[ -z "$SUCCESS_RA_SX" ]] &>/dev/null; then
-    SUCCESS_RA_SX="0"
-  fi
-
-  # success rate with color
-  if [[ "$SUCCESS_RA_SX" -ge "0" ]] &>/dev/null; then
-    SRAC="${GR:?}${SUCCESS_RA:?}%"
-  fi
-  if [[ "$SUCCESS_RA_SX" -ge "10" ]] &>/dev/null; then
-    SRAC="${Y0:?}${SUCCESS_RA:?}%"
-  fi
-  if [[ "$SUCCESS_RA_SX" -ge "25" ]] &>/dev/null; then
-    SRAC="${Y1:?}${SUCCESS_RA:?}%"
-  fi
-  if [[ "$SUCCESS_RA_SX" -ge "50" ]] &>/dev/null; then
-    SRAC="${G0:?}${SUCCESS_RA:?}%"
-  fi
-  if [[ "$SUCCESS_RA_SX" -ge "75" ]] &>/dev/null; then
-    SRAC="${G1:?}${SUCCESS_RA:?}%"
-  fi
-
-  ONION_R=$(cat "${LOG_DIR:?}"/node_data/onion 2>/dev/null)
-  WANIP_R=$(grep "address" "${LOG_DIR:?}"/node_data/getwan 2>&1 |
-    egrep -o "[0-9]+.[0-9]+.[0-9]+.[0-9]+" 2>&1)
-
-  if [[ -z "$ONION_R" ]] &>/dev/null; then
-    # non responsive
-    ONION_R="none"
-  fi
-  if [[ -z "$WANIP_R" ]] &>/dev/null; then
-    # non responsive
-    WANIP_R="none"
-  fi
-
-  # repository head, date and time
-  LATEST_HEAD=$(cd /home/"$(whoami)"/trump-node || exit && git rev-parse --short HEAD 2>&1 |
-    grep -Eo '[a0-z9]{7}' 2>&1 | head -1 2>&1)
-  LATEST_DATE=$(cd /home/"$(whoami)"/trump-node || exit && git log -1 --format="%at" |
-    xargs -I{} date -d @{} '+%Y/%m/%d')
-  LATEST_TIME=$(cd /home/"$(whoami)"/trump-node || exit && git log -1 --format="%at" |
-    xargs -I{} date -d @{} '+%H:%M:%S')
-
-  # average confirmations (average staking/reward time)
-  UNSPENT_COUNT=$(grep "confirmations" "${LOG_DIR:?}"/node_data/listunspent 2>&1 | wc -l 2>&1)
-  UNSPENT_TOTAL=$(grep "confirmations" "${LOG_DIR:?}"/node_data/listunspent 2>&1 |
-    awk '{ print $2 }' 2>&1 | awk '{ SUM += $1} END { print SUM }' 2>&1)
-  # average calculated
-  UNSPENT_AVG=$(echo "$UNSPENT_TOTAL/$UNSPENT_COUNT" 2>&1 | bc 2>&1)
-  # calculate seconds
-  UNSPENT_SEC=$(echo "$UNSPENT_AVG*60" 2>&1 |
-    bc -l 2>&1 | awk -F. '{ print $1 }' 2>&1)
-  # calculate seconds into age
-  UNSPENT_AGE=$(printf '%dh:%dm' $(("$UNSPENT_SEC/3600")) $(("$UNSPENT_SEC%3600/60")))
-  # save the value
-  echo "${UNSPENT_AGE:?}" >"${LOG_DIR:?}"/node_data/avgconfirmation.value
-  UNSPENT_AGE_D=$(echo "$(echo "$UNSPENT_AGE" 2>&1 |
-    egrep -o "[0-9]+h" 2>&1 | tr -d 'h' 2>&1)/24" 2>&1 | bc 2>&1)
-
-  printf '%b' "${GR:?} - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-  printf '%b' "${GR:?}${LOG_DATE:?} Status() SystemTorNet()${N0:?} Onion ${ONION_R:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-  printf '%b' "${GR:?}${LOG_DATE:?} Status() SystemInternet${N0:?} WanIP ${WANIP_R:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-  printf '%b' "${GR:?}${LOG_DATE:?} Status() SystemIntranet${N0:?} Local ${IP_ADDRESS_N:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-  printf '%b' "${GR:?}${LOG_DATE:?} Status() Script.version${N0:?} Repository [${G1:?}${LATEST_HEAD:?}${N0:?}] ${LATEST_DATE:?} ${LATEST_TIME:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-  printf '%b' "${GR:?}${LOG_DATE:?} Status() System.Monitor${N0:?} Load ${LOAD:?} - temp ${CPU_CTEMP:?}°C ${CPU_FTEMP:?}°F ${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-  printf '%b' "${GR:?}${LOG_DATE:?} Status() System.Monitor${N0:?} Free Mem ${FREE_MEM:?}/${TOTAL_MEM:?} - HDDuse ${USED_HDD:?} (${USED_HDD_P:?})${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-  printf '%b' "${GR:?}${LOG_DATE:?} Status() Fail/success()${N0:?} Fail ${R1:?}${FAIL_COUNT:?}${N0:?} Success ${G1:?}$SUCCESS_CO${N0:?} Success Rate ${SRAC:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-  printf '%b' "${GR:?}${LOG_DATE:?} Status() Addnode.Size()${N0:?} Add New Peers ${CY:?}${ADDNODE_SI:?}${N0:?} Addnode Peers ${C1:?}$ADDNODE_PSI${N0:?} Curl/Arp Nodes ${G1:?}$ADDNODE_NOD${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-  printf '%b' "${GR:?}${LOG_DATE:?} Status() Peers.Status()${N0:?} Total ${WALLET_PEERS_TOTAL:?} Latest ${WALLET_PEERS_LATEST:?} Older ${WALLET_PEERS_OTHER:?} - ${G1:?}⇩${N0:?} $DOWNLOAD ${R1:?}⇧${N0:?} $UPLOAD${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-  printf '%b' "${GR:?}${LOG_DATE:?} Status() Proof.Of.Work:${N0:?} PoS ${WALLET_STAKES:?} AVG Time (${UNSPENT_AGE_D:?}d) ${GR:?}${UNSPENT_AGE:?}${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-  printf '%b' "${GR:?} - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
-else
-  printf '%b' "${LOG_DATE:?} Status() System.Monitor Loading wallet${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
 fi
 
 ### debug peer(s) tries/connected ##############################################
