Update

diff --git a/include/functions b/include/functions
--- a/include/functions
+++ b/include/functions
@@ -2,12 +2,12 @@
 
 # By Rainman
 # V20220101
-# 0.8.9.3
+# 0.8.9.6
 
 # shellcheck disable=SC2034  # Unused variables left for readability
 
 # script version for dashbord
-VERSION="v0.8.9.3"
+VERSION="v0.8.9.6"
 
 source /home/pi/pitrump.conf
 source /usr/local/bin/include/color
@@ -508,7 +508,7 @@ fi
 ### personal addnodes ##########################################################
 
 # add addnodes backup if backup is greater
-if ! tail -25 "${WALLET_LOG_DIR:?}"/debug.log 2>&1 | grep "Adding backup peers" &>/dev/null; then
+if ! tail -50 "${WALLET_LOG_DIR:?}"/debug.log 2>&1 | grep "Adding backup peers" &>/dev/null; then
   if [[ "$(wc -l "${WALLET_DIR:?}"/addnodes 2>&1 | awk '{ print $1 }' 2>&1)" -gt "$(wc -l "${LOG_DIR:?}"/node_data/peers/success 2>&1 | awk '{ print $1 }' 2>&1)" ]] &>/dev/null; then
     cat "${WALLET_DIR:?}"/addnodes 2>/dev/null | awk '!a[$0]++' >"${LOG_DIR:?}"/node_data/peers.tmp
     printf '%b' "${LOG_DATE:?} Status() Addnode.Script Adding backup peers! $(wc -l "${WALLET_DIR:?}"/addnodes 2>&1 | awk '{ print $1 }' 2>&1) ${C1:?}>>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
@@ -567,9 +567,12 @@ function failed_peers() {
   DNS_FAILS=$(egrep ".[a-z]" "${LOG_DIR:?}"/node_data/peers/failed 2>&1 | wc -l 2>&1)
   awk '!a[$0]++' "${LOG_DIR:?}"/node_data/peers/failed >"${LOG_DIR:?}"/node_data/peers/failed.clean 2>&1
   mv "${LOG_DIR:?}"/node_data/peers/failed.clean "${LOG_DIR:?}"/node_data/peers/failed 2>&1
-  # greater than n seconds, continue
-  if [[ "$(cat "${LOG_DIR:?}"/node_data/uptime 2>/dev/null)" -gt "300" ]] &>/dev/null; then
-    printf '%b' "${LOG_DATE:?} Status() Addnode.Script Updating failed list! $(wc -l "${LOG_DIR:?}"/node_data/peers/failed 2>&1 | awk '{ print $1 }' 2>&1) ${IPV4_FAILS:?}/${DNS_FAILS:?} ${GR:?}>>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+  # don't run command with intervals, every n minutes, updating api, arp and ticker (updating lists)
+  if [[ ! "$(date '+%T' 2>&1 | egrep "[0-9]+:30:[0-9]+|[0-9]+:00:[0-9]+" 2>&1)" ]] &>/dev/null; then
+    # greater than n seconds, continue
+    if [[ "$(cat "${LOG_DIR:?}"/node_data/uptime 2>/dev/null)" -gt "300" ]] &>/dev/null; then
+      printf '%b' "${LOG_DATE:?} Status() Addnode.Script Updating failed list! $(wc -l "${LOG_DIR:?}"/node_data/peers/failed 2>&1 | awk '{ print $1 }' 2>&1) ${IPV4_FAILS:?}/${DNS_FAILS:?} ${GR:?}>>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
+    fi
   fi
 }
 
@@ -671,7 +674,7 @@ screen -wipe
 exit
 EOF
 
-    # don't run data with intervals, every n minutes, updating api, arp and ticker (updating lists)
+    # don't run script with intervals, every n minutes, updating api, arp and ticker (updating lists)
     if [[ ! "$(date '+%T' 2>&1 | egrep "[0-9]+:30:[0-9]+|[0-9]+:00:[0-9]+" 2>&1)" ]] &>/dev/null; then
 
       # 60s 90s 120s 240s 300s 600s, 900s, 1800s = 30 minutes
