Update

diff --git a/include/functions b/include/functions
--- a/include/functions
+++ b/include/functions
@@ -94,16 +94,16 @@ INTERFACE=$(echo "$IFCONFIG" 2>&1 | grep -E "wlan*|eth*" 2>&1 |
 
 # update wan, update repo (everyday)
 if [[ "$(date +%H%M 2>&1 | grep -Eo "0000" 2>&1)" ]]; then
-  rm "$LOG_DIR"/getwan &>/dev/null
+  rm "$LOG_DIR"/node_data/getwan &>/dev/null
   # update repo
   cd /home/"$(whoami)"/trump-node || exit &&
     git pull -q && bash include/install 2>&1
 fi
 # get wan address
-if [ ! -f "$LOG_DIR"/getwan ]; then
-  host myip.opendns.com resolver1.opendns.com >"$LOG_DIR"/getwan
+if [ ! -f "$LOG_DIR"/node_data/getwan ]; then
+  host myip.opendns.com resolver1.opendns.com >"$LOG_DIR"/node_data/getwan
 fi
-PUBLIC_IP=$(grep "address" "$LOG_DIR"/getwan 2>&1 |
+PUBLIC_IP=$(grep "address" "$LOG_DIR"/node_data/getwan 2>&1 |
   egrep -o "[0-9]+.[0-9]+.[0-9]+.[0-9]+" 2>&1)
 PUBLIC_IP="${C1:?}${PUBLIC_IP:?}${N0:?}"
 
@@ -117,7 +117,7 @@ UPLOAD=$(ifconfig 2>&1 | grep -E "wla*|eth*" 2>&1 |
   awk '{ print $6 $7 }' 2>&1 | tr -d '()' 2>&1)
 
 # tor status
-if grep "127.0.0.1:9050" "$LOG_DIR"/getinfo &>/dev/null; then
+if grep "127.0.0.1:9050" "$LOG_DIR"/node_data/getinfo &>/dev/null; then
   TOR_ICON=$(printf '%b' "${P1:?}P$N0")
 else
   TOR_ICON=$(printf '%b' "${GR:?}P$N0")
@@ -131,23 +131,23 @@ if ! [ -x "$(command -v screen)" ]; then
 fi
 
 # remove empty files
-if [ ! -s "$LOG_DIR"/addnodes ]; then
-  rm "$LOG_DIR"/addnodes &>/dev/null
+if [ ! -s "$LOG_DIR"/node_data/addnodes ]; then
+  rm "$LOG_DIR"/node_data/addnodes &>/dev/null
 fi
-if [ ! -s "$LOG_DIR"/nodes ]; then
-  rm "$LOG_DIR"/nodes &>/dev/null
+if [ ! -s "$LOG_DIR"/node_data/nodes ]; then
+  rm "$LOG_DIR"/node_data/nodes &>/dev/null
 fi
 
 # update addnodes, failed peers, along with ticker price (every hour)
 if [[ "$(date +%M 2>&1 | grep -Eo "00" 2>&1)" ]]; then
-  rm "$LOG_DIR"/nodes &>/dev/null
+  rm "$LOG_DIR"/node_data/nodes &>/dev/null
 fi
 
 # get node list, ticker (api, arp)
-if [ ! -f "$LOG_DIR"/nodes ]; then
+if [ ! -f "$LOG_DIR"/node_data/nodes ]; then
 
   # save "stable/working" peers into file (addnodes - ipv4 address)
-  awk '/:[0-9]+/ && !/]/ {print $2,$3}' "$LOG_DIR"/getpeerinfo 2>&1 |
+  awk '/:[0-9]+/ && !/]/ {print $2,$3}' "$LOG_DIR"/node_data/getpeerinfo 2>&1 |
     grep -v "Core" >>/home/"$(whoami)"/addnodes 2>&1
 
   # clean up and use as "manually addnodes"
@@ -156,20 +156,20 @@ if [ ! -f "$LOG_DIR"/nodes ]; then
   mv /tmp/an /home/"$(whoami)"/addnodes 2>&1
 
   # constantly adding (ipv4+manually added)
-  awk '/:[0-9]+/ && !/]/ {print $1}' /home/"$(whoami)"/addnodes >"$LOG_DIR"/nodes
+  awk '/:[0-9]+/ && !/]/ {print $1}' /home/"$(whoami)"/addnodes >"$LOG_DIR"/node_data/nodes
 
   # add local address (arp) intranet, no ports on these
   arp -a 2>&1 |
     # ignore common default router IP address
     grep -vwE "(192.168.1.1|192.168.0.1|192.168.1.10.1|192.168.2.1|192.168.1.254|192.168.0.30|192.168.0.50|10.0.0.2|10.1.1.1|10.0.1.1|10.0.0.1|10.0.0.138|10.10.1.1)" 2>&1 |
-    egrep -o "[0-9]+.[0-9]+.[0-9]+.[0-9]+" >>"$LOG_DIR"/nodes 2>&1
+    egrep -o "[0-9]+.[0-9]+.[0-9]+.[0-9]+" >>"$LOG_DIR"/node_data/nodes 2>&1
 
   source /usr/local/bin/include/data
 
-  if [ -f "$LOG_DIR"/ticker ]; then
+  if [ -f "$LOG_DIR"/node_data/ticker ]; then
 
     # clean up ticker
-    cat "$LOG_DIR"/ticker 2>&1 | tr -d '"|,' 2>&1 |
+    cat "$LOG_DIR"/node_data/ticker 2>&1 | tr -d '"|,' 2>&1 |
       egrep -o "[a0-z9]+-[0-9]+usd:[0-9]+.[0-9]+" 2>&1 |
       egrep -o "usd:[0-9]+.[0-9]+" 2>&1 | tr -d 'usd:' >/tmp/ticker 2>&1
 
@@ -181,21 +181,21 @@ if [ ! -f "$LOG_DIR"/nodes ]; then
       bc -l 2>&1 | awk '{ printf "%.2f\n", $1 }' >/tmp/ticker 2>&1
 
     # remove old file
-    rm "$LOG_DIR"/ticker &>/dev/null
+    rm "$LOG_DIR"/node_data/ticker &>/dev/null
 
     # move new file into place
-    mv /tmp/ticker "$LOG_DIR"/ticker 2>&1
+    mv /tmp/ticker "$LOG_DIR"/node_data/ticker 2>&1
   fi
 
   # greater than n minutes
   if [[ "$(uptime_cmd)" -gt "5" ]]; then
     # create failed connection list
     egrep -o " to [a0-z9]+.[a0-z9]+.[a0-z9]+.[a0-z9]+:[0-9]+ failed" /home/"$(whoami)"/TrumpCoin/debug.log 2>&1 |
-      awk '!a[$0]++' 2>&1 | sort -n 2>&1 | awk '{ print $2 }' >"$LOG_DIR"/failed 2>&1
+      awk '!a[$0]++' 2>&1 | sort -n 2>&1 | awk '{ print $2 }' >"$LOG_DIR"/node_data/failed 2>&1
     # count failed connections, feed output to debug.log
-    FAIL_COUNT=$(wc -l "$LOG_DIR"/failed 2>&1 | awk '{ print $1 }' 2>&1)
-    ADDNODE_SI=$(wc -l "$LOG_DIR"/addnodes 2>&1 | awk '{ print $1 }' 2>&1)
-    ADDNODE_NOD=$(wc -l "$LOG_DIR"/nodes 2>&1 | awk '{ print $1 }' 2>&1)
+    FAIL_COUNT=$(wc -l "$LOG_DIR"/node_data/failed 2>&1 | awk '{ print $1 }' 2>&1)
+    ADDNODE_SI=$(wc -l "$LOG_DIR"/node_data/addnodes 2>&1 | awk '{ print $1 }' 2>&1)
+    ADDNODE_NOD=$(wc -l "$LOG_DIR"/node_data/nodes 2>&1 | awk '{ print $1 }' 2>&1)
     ADDNODE_PSI=$(wc -l /home/"$(whoami)"/addnodes 2>&1 | awk '{ print $1 }' 2>&1)
     SUCCESS_CO=$(grep -c "New outbound peer" /home/"$(whoami)"/TrumpCoin/debug.log 2>&1)
     SUCCESS_RA=$(echo "100/$(echo "$FAIL_COUNT+$SUCCESS_CO" 2>&1 |
@@ -235,13 +235,13 @@ if [ ! -f "$LOG_DIR"/nodes ]; then
     printf '%b' "${LOG_DATE:?} Status() PeerStatus...: Total ${WALLET_PEERS_TOTAL:?} New ${WALLET_PEERS_LATEST:?} Older ${WALLET_PEERS_OTHER:?} - ${G1:?}⇩${N0:?} $DOWNLOAD ${R1:?}⇧${N0:?} $UPLOAD${N0:?}\n" >>/home/"$(whoami)"/TrumpCoin/debug.log 2>&1
 
     # create a list (addnodes) from nodes
-    shuf "$LOG_DIR"/nodes >"$LOG_DIR"/addnodes 2>&1
+    shuf "$LOG_DIR"/node_data/nodes >"$LOG_DIR"/node_data/addnodes 2>&1
 
     # remove failed connections inside addnodes
-    cat "$LOG_DIR"/addnodes 2>&1 |
-      grep -v -f "$LOG_DIR"/failed >/tmp/clean_addnodes 2>&1
+    cat "$LOG_DIR"/node_data/addnodes 2>&1 |
+      grep -v -f "$LOG_DIR"/node_data/failed >/tmp/clean_addnodes 2>&1
     # setup new file
-    mv /tmp/clean_addnodes "$LOG_DIR"/addnodes 2>&1
+    mv /tmp/clean_addnodes "$LOG_DIR"/node_data/addnodes 2>&1
   else
     printf '%b' "${LOG_DATE:?} Status() SystemMonitor: Loading wallet..${N0:?}\n" >>/home/"$(whoami)"/TrumpCoin/debug.log 2>&1
   fi
@@ -264,7 +264,7 @@ PEERS_TRIES=$(egrep -o "peer=[0-9]+" /home/"$(whoami)"/TrumpCoin/debug.log 2>&1 
 printf '%b' "${LOG_DATE:?} Status() AddNodes.....: ${Y1:?}Adding nodes now!${N0:?} Connected ${G1:?}$PEERS_TRIES${N0:?}\n" >>/home/"$(whoami)"/TrumpCoin/debug.log 2>&1
 while IFS= read -r ADDS; do
   "$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf addnode "$ADDS" onetry 2>&1
-done <"$LOG_DIR"/addnodes
+done <"$LOG_DIR"/node_data/addnodes
 LOG_DATE=$(date '+%Y-%d-%mT%TZ' 2>&1)
 printf '%b' "${LOG_DATE:?} Status() AddNodes.....: ${G1:?}Adding nodes done! ${N0:?}\n" >>/home/"$(whoami)"/TrumpCoin/debug.log 2>&1
 killall screen
@@ -277,21 +277,21 @@ fi
 ### wallet information #########################################################
 
 # collect wallet info, on every update (loop) from client
-"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getblockchaininfo 2>&1 | tr -d '"|,' >"$LOG_DIR"/getblockchaininfo 2>&1
-"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getinfo 2>&1 | tr -d '"|,' >"$LOG_DIR"/getinfo 2>&1
-"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getmempoolinfo 2>&1 | tr -d '"|,' >"$LOG_DIR"/getmempoolinfo 2>&1
-"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getnetworkinfo 2>&1 | tr -d '"|,' >"$LOG_DIR"/getnetworkinfo 2>&1
-"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getpatriotnodecount 2>&1 | tr -d '"|,' >"$LOG_DIR"/getpatriotnodecount 2>&1
-"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getwalletinfo 2>&1 | tr -d '"|,' >"$LOG_DIR"/getwalletinfo 2>&1
-"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf listunspent 2>&1 | tr -d '"|,' >"$LOG_DIR"/listunspent 2>&1
-"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getpeerinfo 2>&1 | tr -d '"|,' >"$LOG_DIR"/getpeerinfo 2>&1
+"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getblockchaininfo 2>&1 | tr -d '"|,' >"$LOG_DIR"/node_data/getblockchaininfo 2>&1
+"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getinfo 2>&1 | tr -d '"|,' >"$LOG_DIR"/node_data/getinfo 2>&1
+"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getmempoolinfo 2>&1 | tr -d '"|,' >"$LOG_DIR"/node_data/getmempoolinfo 2>&1
+"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getnetworkinfo 2>&1 | tr -d '"|,' >"$LOG_DIR"/node_data/getnetworkinfo 2>&1
+"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getpatriotnodecount 2>&1 | tr -d '"|,' >"$LOG_DIR"/node_data/getpatriotnodecount 2>&1
+"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getwalletinfo 2>&1 | tr -d '"|,' >"$LOG_DIR"/node_data/getwalletinfo 2>&1
+"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf listunspent 2>&1 | tr -d '"|,' >"$LOG_DIR"/node_data/listunspent 2>&1
+"$WALLET_DIR"/trumpcoin-cli -datadir=./ -conf="$WALLET_DIR"/trumpcoin.conf getpeerinfo 2>&1 | tr -d '"|,' >"$LOG_DIR"/node_data/getpeerinfo 2>&1
 
 # wallet version
-WALLET_VERSION=$(grep "Core" "$LOG_DIR"/getnetworkinfo 2>&1 |
+WALLET_VERSION=$(grep "Core" "$LOG_DIR"/node_data/getnetworkinfo 2>&1 |
   egrep -o "[0-9]+.[0-9]+.[0-9]+" 2>&1)
 
 # running mainnet or testnet
-if ! "$(grep "main" "$LOG_DIR"/getblockchaininfo 2>&1)" -eq "main" &>/dev/null; then
+if ! "$(grep "main" "$LOG_DIR"/node_data/getblockchaininfo 2>&1)" -eq "main" &>/dev/null; then
   # mainnet
   WALLET_CHAIN="${G0:?}mainnet${N0:?}"
 else
@@ -306,16 +306,16 @@ if [[ "$(uptime_cmd)" -gt "5" ]]; then
   # logo turns yellow while running
   RC="${Y1:?}"
   # headers, blocks, sync
-  WALLET_HEADS=$(grep "blocks" "$LOG_DIR"/getblockchaininfo 2>&1 |
+  WALLET_HEADS=$(grep "blocks" "$LOG_DIR"/node_data/getblockchaininfo 2>&1 |
     grep -Eo "[0-9]+" 2>&1)
-  WALLET_BLOCK=$(grep "headers" "$LOG_DIR"/getblockchaininfo 2>&1 |
+  WALLET_BLOCK=$(grep "headers" "$LOG_DIR"/node_data/getblockchaininfo 2>&1 |
     grep -Eo "[0-9]+" 2>&1)
   WALLET_SYNC=$(echo "100/$WALLET_HEADS*$WALLET_BLOCK" 2>&1 |
     bc -l 2>&1 | awk '{ printf "%.2f\n", $1 }' 2>&1)
   WALLET_SYNC="${G1:?}${WALLET_SYNC:?}%${N0:?}"
 else # wallet is loading/syncing
   # clean up old files, while loading
-  rm -R "${LOG_DIR:?}"/* &>/dev/null
+  rm -R "${LOG_DIR:?}"/node_data/* &>/dev/null
   # loading while waiting on client
   RC_LOADING="${GR:?}        Loading${N0:?}"
   # logo turns grey while loading
@@ -325,71 +325,71 @@ else # wallet is loading/syncing
 fi
 
 # wallet patriotnodes total
-WALLET_NODES_TOTAL=$(grep "total" "$LOG_DIR"/getpatriotnodecount 2>&1 |
+WALLET_NODES_TOTAL=$(grep "total" "$LOG_DIR"/node_data/getpatriotnodecount 2>&1 |
   egrep -o "[0-9]+" 2>&1)
 # wallet patriotnodes stable
-WALLET_NODES_STABLE=$(grep "stable" "$LOG_DIR"/getpatriotnodecount 2>&1 |
+WALLET_NODES_STABLE=$(grep "stable" "$LOG_DIR"/node_data/getpatriotnodecount 2>&1 |
   egrep -o "[0-9]+" 2>&1)
 # wallet patriotnodes enabled
-WALLET_NODES_ENABLED=$(grep "enabled" "$LOG_DIR"/getpatriotnodecount 2>&1 |
+WALLET_NODES_ENABLED=$(grep "enabled" "$LOG_DIR"/node_data/getpatriotnodecount 2>&1 |
   egrep -o "[0-9]+" 2>&1)
 # wallet patriotnodes inqueue
-WALLET_NODES_INQUEUE=$(grep "inqueue" "$LOG_DIR"/getpatriotnodecount 2>&1 |
+WALLET_NODES_INQUEUE=$(grep "inqueue" "$LOG_DIR"/node_data/getpatriotnodecount 2>&1 |
   egrep -o "[0-9]+" 2>&1)
 # wallet connections total
-WALLET_PEERS_TOTAL=$(grep "connections" "$LOG_DIR"/getinfo 2>&1 |
+WALLET_PEERS_TOTAL=$(grep "connections" "$LOG_DIR"/node_data/getinfo 2>&1 |
   egrep -o "[0-9]+" 2>&1)
-if [ -f "$LOG_DIR"/ticker ]; then
+if [ -f "$LOG_DIR"/node_data/ticker ]; then
   WALLET_PEERS_TOTAL="${P1:?}${WALLET_PEERS_TOTAL:?}${N0:?}"
 fi
 # wallet connections latest (using wallet version)
-WALLET_PEERS_LATEST=$(grep "subver" "$LOG_DIR"/getpeerinfo 2>&1 |
+WALLET_PEERS_LATEST=$(grep "subver" "$LOG_DIR"/node_data/getpeerinfo 2>&1 |
   egrep -o "$WALLET_VERSION" 2>&1 | wc -l 2>&1)
-if [ -f "$LOG_DIR"/ticker ]; then
+if [ -f "$LOG_DIR"/node_data/ticker ]; then
   WALLET_PEERS_LATEST="${G1:?}${WALLET_PEERS_LATEST:?}${N0:?}"
 fi
 # wallet connections other (not latest, probably older wallets)
-WALLET_PEERS_OTHER=$(grep "subver" "$LOG_DIR"/getpeerinfo 2>&1 |
+WALLET_PEERS_OTHER=$(grep "subver" "$LOG_DIR"/node_data/getpeerinfo 2>&1 |
   egrep -o "[0-9]+.[0-9]+.[0-9]+" 2>&1 |
   grep -v "$WALLET_VERSION" 2>&1 | wc -l 2>&1)
-if [ -f "$LOG_DIR"/ticker ]; then
+if [ -f "$LOG_DIR"/node_data/ticker ]; then
   WALLET_PEERS_OTHER="${G0:?}${WALLET_PEERS_OTHER:?}${N0:?}"
 fi
-if [ -f "$LOG_DIR"/ticker ]; then
+if [ -f "$LOG_DIR"/node_data/ticker ]; then
   # wallet balance
-  WALLET_BALANCE=$(grep "balance" "$LOG_DIR"/getinfo 2>&1 |
+  WALLET_BALANCE=$(grep "balance" "$LOG_DIR"/node_data/getinfo 2>&1 |
     egrep -o "[0-9]+.[0-9]+" 2>&1 | awk '{ printf "%.2f\n", $1 }' 2>&1)
   # wallet value
-  WALLET_VALUE=$(echo "$(tail -1 "$LOG_DIR"/ticker 2>&1)*$WALLET_BALANCE" 2>&1 |
+  WALLET_VALUE=$(echo "$(tail -1 "$LOG_DIR"/node_data/ticker 2>&1)*$WALLET_BALANCE" 2>&1 |
     bc -l 2>&1 | awk '{ printf "%.2f\n", $1 }' 2>&1)
 fi
-if [ -f "$LOG_DIR"/ticker ]; then
+if [ -f "$LOG_DIR"/node_data/ticker ]; then
   WALLET_VERSION="${G1:?}${WALLET_VERSION:?}${N0:?}"
   # wallet ticker.usd
-  WALLET_TICKER=$(cat "$LOG_DIR"/ticker 2>&1)
+  WALLET_TICKER=$(cat "$LOG_DIR"/node_data/ticker 2>&1)
   # wallet mempool
-  WALLET_MEMPOOL=$(grep "size" "$LOG_DIR"/getmempoolinfo 2>&1 |
+  WALLET_MEMPOOL=$(grep "size" "$LOG_DIR"/node_data/getmempoolinfo 2>&1 |
     egrep -o "[0-9]+" 2>&1)
   # wallet txcount
-  WALLET_TXCOUNT=$(grep "txcount" "$LOG_DIR"/getwalletinfo 2>&1 |
+  WALLET_TXCOUNT=$(grep "txcount" "$LOG_DIR"/node_data/getwalletinfo 2>&1 |
     egrep -o "[0-9]+" 2>&1)
   # wallet inputs
-  WALLET_INPUTS=$(grep "address" "$LOG_DIR"/listunspent 2>&1 | wc -l 2>&1)
+  WALLET_INPUTS=$(grep "address" "$LOG_DIR"/node_data/listunspent 2>&1 | wc -l 2>&1)
 # last txid, (smallest one)
 fi
-LAST_TX=$(grep "confirmations" "$LOG_DIR"/listunspent 2>&1 |
+LAST_TX=$(grep "confirmations" "$LOG_DIR"/node_data/listunspent 2>&1 |
   awk '{ print $2 }' 2>&1 | sort -n 2>&1 | head -1 2>&1)
 # wallet txid with help of last_tx var
-WALLET_TXLAST=$(cat "$LOG_DIR"/listunspent 2>&1 | tr -d ':' 2>&1 |
+WALLET_TXLAST=$(cat "$LOG_DIR"/node_data/listunspent 2>&1 | tr -d ':' 2>&1 |
   grep -B8 "confirmations $LAST_TX" 2>&1 | grep "txid" 2>&1 |
   awk '{ print $2 }' 2>&1 | tail -1 2>&1)
 # wallet stakes (addtowallet)
 # create staking log
-grep "AddToWallet" "$WALLET_DIR"/debug.log >"$LOG_DIR"/staking
-WALLET_STAKES=$(grep -c "AddToWallet" "$LOG_DIR"/staking 2>&1)
-if [ -f "$LOG_DIR"/ticker ]; then
+grep "AddToWallet" "$WALLET_DIR"/debug.log >"$LOG_DIR"/node_data/staking
+WALLET_STAKES=$(grep -c "AddToWallet" "$LOG_DIR"/node_data/staking 2>&1)
+if [ -f "$LOG_DIR"/node_data/ticker ]; then
   # wallet pos status
-  if [[ "$(grep "Staking Active" "$LOG_DIR"/getinfo 2>&1)" ]]; then
+  if [[ "$(grep "Staking Active" "$LOG_DIR"/node_data/getinfo 2>&1)" ]]; then
     # pos active
     POS_STATUS="${G1:?}S${N0:?}"
     # balance is staking, highlight balance, stakes and inputs
@@ -415,14 +415,14 @@ fi
 ### timeline ###################################################################
 
 # if rpc in warm-up, loading block index, wait
-if [ -f "$LOG_DIR"/getblockchaininfo ]; then
+if [ -f "$LOG_DIR"/node_data/getblockchaininfo ]; then
 
   # random start number
   RANDOM_TIMELINE=$((((RANDOM % 12) + 1)))
 
   # difficulty
   if [ "$RANDOM_TIMELINE" -eq "1" ]; then
-    TIMELINE=$(grep "difficulty" "$LOG_DIR"/getinfo 2>&1 |
+    TIMELINE=$(grep "difficulty" "$LOG_DIR"/node_data/getinfo 2>&1 |
       awk '{ print $2 }' 2>&1 | awk '{ printf "%.2f\n", $1 }' 2>&1)
     TIMELINE="Difficulty $TIMELINE"
   # patriotnodes
@@ -430,23 +430,23 @@ if [ -f "$LOG_DIR"/getblockchaininfo ]; then
     TIMELINE="Patriotnodes ${N0:?}${WALLET_NODES_STABLE:?}${N0:?}/${G1:?}${WALLET_NODES_TOTAL:?}${N0:?}/${G1:?}${WALLET_NODES_ENABLED:?}${N0:?}/${GR:?}${WALLET_NODES_INQUEUE:?}${N0:?}"
   # moneysupply
   elif [ "$RANDOM_TIMELINE" -eq "3" ]; then
-    TIMELINE=$(grep "moneysupply" "$LOG_DIR"/getinfo 2>&1 |
+    TIMELINE=$(grep "moneysupply" "$LOG_DIR"/node_data/getinfo 2>&1 |
       awk '{ print $2 }' 2>&1 | awk '{ printf "%.0f\n", $1 }' 2>&1 | rev 2>&1 |
       sed "s#[[:digit:]]\{3\}#&,#g" 2>&1 | rev 2>&1 | sed 's/^,//g' 2>&1)
     TIMELINE="Moneysupply $TIMELINE"
   # unconfirmed_balance
   elif [ "$RANDOM_TIMELINE" -eq "4" ]; then
-    TIMELINE=$(grep "unconfirmed_balance" "$LOG_DIR"/getwalletinfo 2>&1 |
+    TIMELINE=$(grep "unconfirmed_balance" "$LOG_DIR"/node_data/getwalletinfo 2>&1 |
       awk '{ print $2 }' 2>&1 | awk '{ printf "%.2f\n", $1 }' 2>&1)
     TIMELINE="Unconfirmed ${GR:?}$TIMELINE${N0:?}"
   # immature_balance
   elif [ "$RANDOM_TIMELINE" -eq "5" ]; then
-    TIMELINE=$(grep "immature_balance" "$LOG_DIR"/getwalletinfo 2>&1 |
+    TIMELINE=$(grep "immature_balance" "$LOG_DIR"/node_data/getwalletinfo 2>&1 |
       awk '{ print $2 }' 2>&1 | awk '{ printf "%.2f\n", $1 }' 2>&1)
     TIMELINE="Immature ${GR:?}$TIMELINE${N0:?}"
   elif [ "$RANDOM_TIMELINE" -eq "6" ]; then
     # lowest confirmation
-    TIMELINE_CONF=$(grep "confirmations" "$LOG_DIR"/listunspent 2>&1 |
+    TIMELINE_CONF=$(grep "confirmations" "$LOG_DIR"/node_data/listunspent 2>&1 |
       awk '{ print $2 }' 2>&1 | sort -n 2>&1 | head -1 2>&1)
     # calculate seconds
     TIMELINE_SEC=$(echo "$TIMELINE_CONF*60" 2>&1 |
@@ -458,7 +458,7 @@ if [ -f "$LOG_DIR"/getblockchaininfo ]; then
     TIMELINE="New Input ${C1:?}$TIMELINE_CONF${N0:?} ${INPUT_AGE_D:?}d ${GR:?}$INPUT_AGE${N0:?}"
   elif [ "$RANDOM_TIMELINE" -eq "7" ]; then
     # highest confirmation
-    TIMELINE_CONF=$(grep "confirmations" "$LOG_DIR"/listunspent 2>&1 |
+    TIMELINE_CONF=$(grep "confirmations" "$LOG_DIR"/node_data/listunspent 2>&1 |
       awk '{ print $2 }' 2>&1 | sort -n 2>&1 | tail -1 2>&1)
     # calculate seconds
     TIMELINE_SEC=$(echo "$TIMELINE_CONF*60" 2>&1 |
@@ -470,8 +470,8 @@ if [ -f "$LOG_DIR"/getblockchaininfo ]; then
     TIMELINE="Old Input ${G1:?}$TIMELINE_CONF${N0:?} ${INPUT_AGE_D:?}d ${GR:?}$INPUT_AGE${N0:?}"
     # average confirmation
   elif [ "$RANDOM_TIMELINE" -eq "8" ]; then
-    UNSPENT_COUNT=$(grep "confirmations" "$LOG_DIR"/listunspent | wc -l)
-    TIMELINE=$(grep "confirmations" "$LOG_DIR"/listunspent 2>&1 |
+    UNSPENT_COUNT=$(grep "confirmations" "$LOG_DIR"/node_data/listunspent | wc -l)
+    TIMELINE=$(grep "confirmations" "$LOG_DIR"/node_data/listunspent 2>&1 |
       awk '{ print $2 }' 2>&1 | awk '{ SUM += $1} END { print SUM }' 2>&1)
     # average calculated
     TIMELINE_AVG=$(echo "$TIMELINE/$UNSPENT_COUNT" 2>&1 | bc 2>&1)
@@ -488,12 +488,12 @@ if [ -f "$LOG_DIR"/getblockchaininfo ]; then
     TIMELINE="Value${G0:?} ${WALLET_VALUE:?} USD ${GR:?}$WALLET_TICKER${N0:?}"
     # highest input amount
   elif [ "$RANDOM_TIMELINE" -eq "10" ]; then
-    TIMELINE=$(grep "amount" "$LOG_DIR"/listunspent 2>&1 |
+    TIMELINE=$(grep "amount" "$LOG_DIR"/node_data/listunspent 2>&1 |
       awk '{ print $2 }' 2>&1 | sort -n 2>&1 | tail -1 2>&1)
     TIMELINE="Highest Input ${G1:?}$TIMELINE${N0:?}"
     # lowest input amount
   elif [ "$RANDOM_TIMELINE" -eq "11" ]; then
-    TIMELINE=$(grep "amount" "$LOG_DIR"/listunspent 2>&1 |
+    TIMELINE=$(grep "amount" "$LOG_DIR"/node_data/listunspent 2>&1 |
       awk '{ print $2 }' 2>&1 | sort -n 2>&1 | head -1 2>&1)
     TIMELINE="Lowest Input ${G1:?}$TIMELINE${N0:?}"
   elif [ "$RANDOM_TIMELINE" -eq "12" ]; then
