Update

diff --git a/include/install b/include/install
--- a/include/install
+++ b/include/install
@@ -199,4 +199,29 @@ fi
 
 bash /etc/pi-node/include/find
 
+################################################################################
+# missing wallet daemon or client
+################################################################################
+
+# if no daemon found, if no client found
+if [[ "$DAE_FOUND_CTRL" == "null" || -z "$CLI_FOUND_CTRL" ]] &>/dev/null; then
+  printf '%b' "[${G1}OK${N0}] Dae/Cli : Not Found ${CY}$DAE_FOUND${N0}!\n"
+  # linux
+  LATEST_RELEASE="$(curl -s https://github.com/FreedomCoin-Project/FreedomCoin-Core/releases/latest | html2text 2>&1 | egrep -A1 "Releases" 2>&1 | tail -1 2>&1 | awk '{ print $2 }')"
+  printf '%b' "[${G1}OK${N0}] Release : Checking latest release!\n"
+  # change directory
+  cd || exit && wget -c https://github.com/FreedomCoin-Project/FreedomCoin-Core/releases/download/"$LATEST_RELEASE"/FreedomCoin-Core-Linux.zip
+  printf '%b' "[${G1}OK${N0}] WGet    : Download complete!\n"
+  # unzip file
+  unzip FreedomCoin-Core-Linux.zip
+  printf '%b' "[${G1}OK${N0}] ZIP     : Unzip complete!\n"
+  # change directory
+  cd FreedomCoin-Core-Linux || exit
+  # sudo copy
+  sudo cp freedomCoin* /usr/local/bin
+  # fix ownership
+  sudo chown "$(whoami)":"$(whoami)" /usr/local/bin/freedomcoin*
+  printf '%b' "[${G1}OK${N0}] Owner   : Fixing ownership!\n"
+fi
+
 # END
