Update

diff --git a/include/install b/include/install
--- a/include/install
+++ b/include/install
@@ -92,7 +92,7 @@ MOD_FOUND="$(grep "Model" /proc/cpuinfo | awk -F: '{ print $2 }' | xargs)"
 
 # if zero
 if [[ -z "$MOD_FOUND" ]] &>/dev/null; then
-  MOD_FOUND="$(grep "vendor_id" /proc/cpuinfo)"
+  MOD_FOUND="$(grep "vendor_id" /proc/cpuinfo | awk -F: '{ print $2 }')"
 fi
 
 ################################################################################
@@ -225,141 +225,147 @@ bash /etc/pi-node/include/find
 # missing wallet daemon or client
 ################################################################################
 
-# if no daemon found, if no client found
-if [[ ! -f /usr/local/bin/freedomcoind && ! -f /usr/local/bin/freedomcoin-cli ]] &>/dev/null; then
-  printf '%b' "[${G1}OK${N0}] Dae/Cli : Not Found ${CY}$DAE_FOUND${N0}!\n"
-  # linux
-  LATEST_RELEASE="$(curl -s https://api.github.com/repos/FreedomCoin-Project/FreedomCoin-Core/releases/latest | grep '"tag_name"' | cut -d '"' -f 4)"
-  printf '%b' "[${G1}OK${N0}] curl    : Checking latest release!\n"
+# if VPS already, skip this
+if [[ -d "$HOME"/freed1 ]] &>/dev/null; then
+  printf '%b' "[${G1}OK${N0}] Dae/Cli : This is a VPS Server already!\n"
+else
 
-  # machine
-  UNAME_M="$(uname -m)"
+  # if no daemon found, if no client found
+  if [[ ! -f /usr/local/bin/freedomcoind && ! -f /usr/local/bin/freedomcoin-cli ]] &>/dev/null; then
+    printf '%b' "[${Y1}Ok${N0}] Dae/Cli : Not Found ${CY}$DAE_FOUND${N0}!\n"
+    # linux
+    LATEST_RELEASE="$(curl -s https://api.github.com/repos/FreedomCoin-Project/FreedomCoin-Core/releases/latest | grep '"tag_name"' | cut -d '"' -f 4)"
+    printf '%b' "[${G1}OK${N0}] curl    : Checking latest release!\n"
 
-  if [[ "$(echo "$UNAME_M" | grep -c "x86_64")" == "1" ]] &>/dev/null; then
-    # x86_64
-    WALLET_DOWNLOAD="FreedomCoin-Core-Linux.zip"
-  fi
-  if [[ "$(echo "$UNAME_M" | grep -c "aarch64")" == "1" ]] &>/dev/null; then
-    # aarch64
-    WALLET_DOWNLOAD="FreedomCoin-Core-Linux.zip"
-  fi
-  if [[ "$(echo "$UNAME_M" | grep -c "arm")" == "1" ]] &>/dev/null; then
-    # arm
-    WALLET_DOWNLOAD="FreedomCoin_arm.zip"
-  fi
+    # machine
+    UNAME_M="$(uname -m)"
 
-  # if missing
-  if [[ ! -f "$HOME"/"$WALLET_DOWNLOAD".zip ]] &>/dev/null; then
-    # change directory, download WALLET_DOWNLOAD.zip
-    cd || exit && wget -c https://github.com/FreedomCoin-Project/FreedomCoin-Core/releases/download/"$LATEST_RELEASE"/"$WALLET_DOWNLOAD".zip
-    printf '%b' "[${G1}OK${N0}] wget    : Download complete!\n"
-  fi
-  # if missing
-  if [[ ! -d "$HOME"/"$WALLET_DOWNLOAD" ]] &>/dev/null; then
-    # unzip file
-    unzip "$WALLET_DOWNLOAD".zip
-    printf '%b' "[${G1}OK${N0}] unzip   : Unzip complete!\n"
-  fi
-  # change directory
-  cd "$HOME"/"$WALLET_DOWNLOAD" || exit
-  # if found
-  if [[ -f freedomcoin-cli ]] &>/dev/null; then
-    # if not installed
-    if [[ ! -f /usr/local/bin/freedomcoin-cli ]] &>/dev/null; then
-      # install
-      sudo mv freedomcoin-cli /usr/local/bin
-      printf '%b' "[${G1}OK${N0}] mv      : freedomcoin-cli installed!\n"
-    else
-      printf '%b' "[${G1}OK${N0}] mv      : freedomcoin-cli already installed!\n"
+    if [[ "$(echo "$UNAME_M" | grep -c "x86_64")" == "1" ]] &>/dev/null; then
+      # x86_64
+      WALLET_DOWNLOAD="FreedomCoin-Core-Linux"
     fi
-  fi
-  # if found
-  if [[ -f freedomcoind ]] &>/dev/null; then
-    # if not installed
-    if [[ ! -f /usr/local/bin/freedomcoind ]] &>/dev/null; then
-      # install
-      sudo mv freedomcoind /usr/local/bin
-      printf '%b' "[${G1}OK${N0}] mv      : freedomcoind installed!\n"
-    else
-      printf '%b' "[${G1}OK${N0}] mv      : freedomcoind already installed!\n"
+    if [[ "$(echo "$UNAME_M" | grep -c "aarch64")" == "1" ]] &>/dev/null; then
+      # aarch64
+      WALLET_DOWNLOAD="FreedomCoin-Core-Linux"
     fi
-  fi
-  # fix ownership
-  sudo chown "$(whoami)":"$(whoami)" /usr/local/bin/freedomcoin*
-  printf '%b' "[${G1}OK${N0}] chown   : Fixing ownership!\n"
-else
-  printf '%b' "[${G1}OK${N0}] Dae/Cli : FreedomCoin Daemon and Client installed!\n"
-fi
+    if [[ "$(echo "$UNAME_M" | grep -c "arm")" == "1" ]] &>/dev/null; then
+      # arm
+      WALLET_DOWNLOAD="FreedomCoin_arm"
+    fi
 
-################################################################################
-# wallet configuration
-################################################################################
-
-# old pi-node data configuration
-DATA_DIR="$(grep "DATA_DIR=" /usr/local/bin/include/pinode/pinode.conf | awk -F= '{ print $2 }' | awk '{ print $1 }' | tr -d '"')"
-if [[ -n "$DATA_DIR" ]] &>/dev/null; then
-  printf '%b' "[${G1}OK${N0}] Pi-Node : Old data directory found!\n"
-else
-  # run default
-  DATA_DIR="."
-fi
-
-# old pi-node log configuration
-WALLET_LOG_DIR="$(grep "WALLET_LOG_DIR=" /usr/local/bin/include/pinode/pinode.conf | awk -F= '{ print $2 }' | awk '{ print $1 }' | tr -d '"')"
-if [[ -n "$WALLET_LOG_DIR" ]] &>/dev/null; then
-  printf '%b' "[${G1}OK${N0}] Pi-Node : Old log directory found!\n"
-else
-  # run default
-  WALLET_LOG_DIR="."
-fi
-
-# old pi-node wallet configuration
-WALLET_CONFIG="$(grep "WALLET_CONFIG=" /usr/local/bin/include/pinode/pinode.conf | awk -F= '{ print $2 }' | awk '{ print $1 }' | tr -d '"')"
-if [[ -n "$WALLET_CONFIG" ]] &>/dev/null; then
-  printf '%b' "[${G1}OK${N0}] Pi-Node : Old wallet config found!\n"
-else
-  # run default
-  WALLET_CONFIG="."
-fi
-
-# old pi-node proxy configuration
-PROXY="$(grep "PROXY=" /usr/local/bin/include/pinode/pinode.conf | awk -F= '{ print $2 }' | awk '{ print $1 }' | tr -d '"')"
-if [[ -n "$PROXY" ]] &>/dev/null; then
-  printf '%b' "[${G1}OK${N0}] Pi-Node : Old proxy setup found!\n"
-  # check for tor install
-  if ! [ -x "$(command -v git)" ]; then
-    printf '%b' "[${G1}OK${N0}] Proxy   : Installing tor!\n"
-    sudo apt-get install tor -y
     # if missing
-    if [[ "$(grep -c "FreedomCoin-service" /etc/tor/torrc)" -eq "0" ]] &>/dev/null; then
-      # update tor configuration
-      printf '%b' "[${G1}OK${N0}] Proxy   : Updating configuration!\n"
-      echo "HiddenServiceDir /var/lib/tor/FreedomCoin-service/
+    if [[ ! -f "$HOME"/"$WALLET_DOWNLOAD".zip ]] &>/dev/null; then
+      # change directory, download WALLET_DOWNLOAD.zip
+      cd || exit && wget -c https://github.com/FreedomCoin-Project/FreedomCoin-Core/releases/download/"$LATEST_RELEASE"/"$WALLET_DOWNLOAD".zip
+      printf '%b' "[${G1}OK${N0}] wget    : Download complete!\n"
+    fi
+    # if missing
+    if [[ ! -d "$HOME"/"$WALLET_DOWNLOAD" ]] &>/dev/null; then
+      # unzip file
+      unzip "$WALLET_DOWNLOAD".zip
+      printf '%b' "[${G1}OK${N0}] unzip   : Unzip complete!\n"
+    fi
+    # change directory
+    cd "$HOME"/"$WALLET_DOWNLOAD" || exit
+    # if found
+    if [[ -f freedomcoin-cli ]] &>/dev/null; then
+      # if not installed
+      if [[ ! -f /usr/local/bin/freedomcoin-cli ]] &>/dev/null; then
+        # install
+        sudo mv freedomcoin-cli /usr/local/bin
+        printf '%b' "[${G1}OK${N0}] mv      : freedomcoin-cli installed!\n"
+      else
+        printf '%b' "[${G1}OK${N0}] mv      : freedomcoin-cli already installed!\n"
+      fi
+    fi
+    # if found
+    if [[ -f freedomcoind ]] &>/dev/null; then
+      # if not installed
+      if [[ ! -f /usr/local/bin/freedomcoind ]] &>/dev/null; then
+        # install
+        sudo mv freedomcoind /usr/local/bin
+        printf '%b' "[${G1}OK${N0}] mv      : freedomcoind installed!\n"
+      else
+        printf '%b' "[${G1}OK${N0}] mv      : freedomcoind already installed!\n"
+      fi
+    fi
+    # fix ownership
+    sudo chown "$(whoami)":"$(whoami)" /usr/local/bin/freedomcoin*
+    printf '%b' "[${G1}OK${N0}] chown   : Fixing ownership!\n"
+  else
+    printf '%b' "[${G1}OK${N0}] Dae/Cli : FreedomCoin Daemon and Client installed!\n"
+  fi
+
+  ##############################################################################
+  # wallet configuration
+  ##############################################################################
+
+  # old pi-node data configuration
+  DATA_DIR="$(grep "DATA_DIR=" /usr/local/bin/include/pinode/pinode.conf | awk -F= '{ print $2 }' | awk '{ print $1 }' | tr -d '"')"
+  if [[ -n "$DATA_DIR" ]] &>/dev/null; then
+    printf '%b' "[${G1}OK${N0}] Pi-Node : Old data directory found!\n"
+  else
+    # run default
+    DATA_DIR="."
+  fi
+
+  # old pi-node log configuration
+  WALLET_LOG_DIR="$(grep "WALLET_LOG_DIR=" /usr/local/bin/include/pinode/pinode.conf | awk -F= '{ print $2 }' | awk '{ print $1 }' | tr -d '"')"
+  if [[ -n "$WALLET_LOG_DIR" ]] &>/dev/null; then
+    printf '%b' "[${G1}OK${N0}] Pi-Node : Old log directory found!\n"
+  else
+    # run default
+    WALLET_LOG_DIR="."
+  fi
+
+  # old pi-node wallet configuration
+  WALLET_CONFIG="$(grep "WALLET_CONFIG=" /usr/local/bin/include/pinode/pinode.conf | awk -F= '{ print $2 }' | awk '{ print $1 }' | tr -d '"')"
+  if [[ -n "$WALLET_CONFIG" ]] &>/dev/null; then
+    printf '%b' "[${G1}OK${N0}] Pi-Node : Old wallet config found!\n"
+  else
+    # run default
+    WALLET_CONFIG="."
+  fi
+
+  # old pi-node proxy configuration
+  PROXY="$(grep "PROXY=" /usr/local/bin/include/pinode/pinode.conf | awk -F= '{ print $2 }' | awk '{ print $1 }' | tr -d '"')"
+  if [[ -n "$PROXY" ]] &>/dev/null; then
+    printf '%b' "[${G1}OK${N0}] Pi-Node : Old proxy setup found!\n"
+    # check for tor install
+    if ! [ -x "$(command -v git)" ]; then
+      printf '%b' "[${G1}OK${N0}] Proxy   : Installing tor!\n"
+      sudo apt-get install tor -y
+      # if missing
+      if [[ "$(grep -c "FreedomCoin-service" /etc/tor/torrc)" -eq "0" ]] &>/dev/null; then
+        # update tor configuration
+        printf '%b' "[${G1}OK${N0}] Proxy   : Updating configuration!\n"
+        echo "HiddenServiceDir /var/lib/tor/FreedomCoin-service/
 HiddenServicePort 15110 127.0.0.1:15110" | sudo tee -a /etc/tor/torrc >/dev/null
-      # update tor configuration
-      printf '%b' "[${G1}OK${N0}] Proxy   : Restarting tor!\n"
-      sudo service tor@default restart
+        # update tor configuration
+        printf '%b' "[${G1}OK${N0}] Proxy   : Restarting tor!\n"
+        sudo service tor@default restart
+      fi
     fi
   fi
-fi
 
-################################################################################
-# bootstrap
-################################################################################
+  ##############################################################################
+  # bootstrap
+  ##############################################################################
 
-bash /etc/pi-node/include/bootstrap
+  bash /etc/pi-node/include/bootstrap
 
-################################################################################
-# start wallet daemon
-################################################################################
+  ##############################################################################
+  # start wallet daemon
+  ##############################################################################
 
-# daemon running
-if [[ "$(pidof freedomcoind | wc -l)" -gt "0" ]] &>/dev/null; then
-  printf '%b' "[${G1}OK${N0}] Daemon  : Already running! PID: $DAE_PID\n"
-else
-  printf '%b' "[${G1}OK${N0}] Daemon  : Starting daemon..\n"
-  # start daemon
-  ./freedomcoind -datadir="${DATA_DIR:?}" -debuglogfile="${WALLET_LOG_DIR:?}"/debug.log -conf="${DATA_DIR:?}"/"${WALLET_CONFIG:?}" -debug=tor -proxy="${PROXY:?}" -daemon
+  # daemon running
+  if [[ "$(pidof freedomcoind | wc -l)" -gt "0" ]] &>/dev/null; then
+    printf '%b' "[${G1}OK${N0}] Daemon  : Already running! PID: $DAE_PID\n"
+  else
+    printf '%b' "[${G1}OK${N0}] Daemon  : Starting daemon..\n"
+    # start daemon
+    ./freedomcoind -datadir="${DATA_DIR:?}" -debuglogfile="${WALLET_LOG_DIR:?}"/debug.log -conf="${DATA_DIR:?}"/"${WALLET_CONFIG:?}" -debug=tor -proxy="${PROXY:?}" -daemon
+  fi
 fi
 
 # END
